### ISSUE TITLE
change: upgrade threejs version

### ISSUE THREAD

**Issue by eviltik** [NikLever/CanvasUI#28]
We are using r119. 

In oculus browser, we have a non blocking error

```
The WebGL context was not marked as XR compatible. Call MakeXRCompatible to mark it as such. This will result in a fatal error in the future. See https://immersive-web.github.io/webxr/#dom-webglrenderingcontextbase-makexrcompatible
```

We should upgrade at least r125.

I've tested with r135, everything is smooth.

@NikLever are you ok for r135 ?

**Comment by NikLever** [comment]
Very happy to switch to r135
