### ISSUE TITLE
not working properly with OrthographicCamera?

### ISSUE THREAD

**Issue by whitesoundcl** [NikLever/CanvasUI#3]
I am trying to use a isometric camera with CanvasUI for the UI elements but i cannot set the ui closer to the camera.
Say for example we have this code: 
```javascript
    const d = 60;
    var width = window.innerWidth;
    var height = window.innerHeight;
    var aspect = width / height;
// add camera
    const camera = new THREE.OrthographicCamera(
      -d * aspect,
      d * aspect,
      d,
      -d,
      1,
      1000
    );
   
    camera.position.set(22, 22, 22);
    ui = new CanvasUI(
      {
        header: "WHY",
        main: "This is the main text",
        footer: "Footer",
      },
      {
        header: {
          type: "text",
          position: { top: 0 },
          paddingTop: 10,
          height: 70,
        },
        main: {
          type: "text",
          position: { top: 70 },
          height: 372, // default height is 512 so this is 512 - header height:70 - footer height:70
          backgroundColor: "#bbb",
          fontColor: "#000",
        },
        footer: {
          type: "text",
          position: { bottom: 0 },
          paddingTop: 30,
          height: 70,
        },
      }
    );

    camera.attach(ui.mesh);
    ui.mesh.position.set(0, 0, -99); // it does not matter how close or far i set the camera position, it won't change at all. (Z)
    ui.add(uiRef.current.mesh);


```

Pretty sure that i must be doing something wrong, but is what i see all the time: 
![imagen](https://user-images.githubusercontent.com/22988648/130370275-d25e0e47-96e9-46b1-8f9c-ec04bc6d560d.png)
Just a small rectangle.

Is there a way to use this framework with OrthographicCamera?

**Comment by NikLever** [comment]
Hi
Change the panelSize. By default it is set to 1m square.

defaultconfig = {
	panelSize: { width: 1, height: 1},

Cheers Nik

Nicholas Lever, 28 Platt Lane, Dobcross, Oldham, OL3 5QD
t: 0797 370 2959 e: ***@***.***

**Comment by whitesoundcl** [comment]
That actually solved the problem. The solution was right in front of me :man_facepalming:  Thanks for taking the time to answer
