### ISSUE TITLE
change: examples common code

### ISSUE THREAD

**Issue by eviltik** [NikLever/CanvasUI#35]
Plenty of code in examples can be stored in one js class witch can be extended :

App:
* constructor
* initScene
* setupXR
* resize
* render

Final code example:
```
import { Environnement } from '../Environnement.js';
import { CanvasUI } from '../../jsm/CanvasUI.js';

class App extends Environnement {
    constructor() {
        super();
    }

    createUI() {
        ...
    }

}
```

The Environnement class will have little methods like setupRenderer, setupCamera, so we can override methods in the main class easily.

@NikLever will you accept this change ?

**Comment by eviltik** [comment]
related to #33

**Comment by eviltik** [comment]
is it ok for you @NikLever ? ty

**Comment by NikLever** [comment]
I don't want to leave users feeling they need to use a helper class with CanvasUI. So on balance I don't like the idea. But you could convince me. BTW Environnement is spelt Environment in English. Probably best to use the English spelling.

**Comment by eviltik** [comment]
> I don't want to leave users feeling they need to use a helper class with CanvasUI. 

I can understand ! It's more easy for users.

Wont fix.
